dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy"
  - "pypy3"
  - "pypy3.5"

install:
  - python -c "import sys, platform, struct;
    print(sys.platform, platform.machine(), struct.calcsize('P')*8)"
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - py.test --cov=persiantools tests/ -v
  - black persiantools/ setup.py --check -l 100

after_success:
  coveralls
